### ISSUE TITLE
Error when adding new platform (missing variable)

### ISSUE THREAD

**Issue by ohh2ahh** [EddyVerbruggen/Custom-URL-scheme#60]
I always get an error when adding a new platform with Cordova when the plugin is already installed. It seems that Cordova tries to install your plugin without the scheme variable.

Workaround: Remove plugin, add platform, re-install plugin.

* LaunchMyApp: 3.2.2.
* Cordova: 4.1.2
* OSX Yosemite 10.10.1

```
Installing "nl.x-services.plugins.launchmyapp" for browser
Failed to install 'nl.x-services.plugins.launchmyapp':Error: Variable(s) missing: URL_SCHEME
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:304:23
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:419:13)
Error: Variable(s) missing: URL_SCHEME
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:304:23
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:419:13)
```

**Comment by PLEEROCK** [comment]
+1

**Comment by EddyVerbruggen** [comment]
This needs to be reported to the [plugman guys](https://issues.apache.org/jira/browse/CB/component/12320402/) I'm afraid.

**Comment by ndtan** [comment]
I had the same issues on my Mac.
Everything's okey on Windows.
